### ISSUE TITLE
Application.properties

### ISSUE THREAD

**Issue by ilsaul** [kemitix/spring-boot-awt-gui-demo#2]
Application.properties can't be read in a client java application. Can you remove it or can you use in the example?

**Comment by kemitix** [comment]
The `applications.properties` file is read by Spring Boot as part of the externalised configuration. See https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config for details on how you can use the file. The file in this project just happens to be empty.
